# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='slug_url',
            field=models.SlugField(default='update_me'),
        ),
    ]
