# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_info', '0002_fund_slug_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='cash_allocation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_allocation',
            field=models.FloatField(default=0.0),
        ),
    ]
